import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    images: [
      {
        url: "/images/share-image.jpg",
        width: 800,
        height: 600,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/bcdf405993.js"
          crossOrigin="anonymous"
        ></script>
        <meta name="description" content="Engitech" />
        <meta name="keywords" content="Engitech" />
        <meta property="og:title" content="Engitech" />
        <meta property="og:description" content="Engitech" />
        <meta
          property="og:image"
          content="/images/share-image.jpg"
        />
        <meta property="og:image:width" content="800" />
        <meta property="og:image:height" content="600" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="page" className="site">
          {children}
        </div>
      </body>
    </html>
  );
}
